### ISSUE TITLE
Create asset isn't working

### ISSUE THREAD

**Issue by digitalronin** [digitalronin/uplink-asset-demo#1]
After configuring `create_asset.py` with the private key and the account address which were generated using `create_account.py` I should be able to use the script to create a new asset. 

But, when I run it, I get the following error:

```
Traceback (most recent call last):
  File "create_asset.py", line 19, in <module>
    issuer=address
  File "./venv/lib/python3.7/site-packages/uplink/client.py", line 416, in uplink_create_asset
    r, s = hdr.sign(private_key)
  File "./venv/lib/python3.7/site-packages/uplink/protocol.py", line 65, in sign
    return ecdsa_sign(privkey, stream, k=k)
  File "./venv/lib/python3.7/site-packages/uplink/cryptography.py", line 122, in ecdsa_sign
    sig = sk.sign(msg, hashfunc=sha3.sha3_256, k=k)
AttributeError: 'bytes' object has no attribute 'sign'
```

I'm not sure why this is happening.

Python: 3.7

**Comment by sdiehl** [comment]
The create asset function is expecting a signing key object instead of a bytestring form of the key. Can generate the Python objects for the keys using the ecdsa_new and unpacking the tuple.

```python
pk1, sk1 = ecdsa_new()
new_account_1 = create_account(pk1, sk1, {'Name': 'Alice'})

supply = 1000000
asset_name = "MYTOKEN"

asset = rpc.uplink_create_asset(
    private_key   = sk1,
    origin        = new_account_1.address,
    name          = asset_name,
    supply        = supply,
    asset_type_nm = "Discrete",
    reference     = "Token",
    issuer        = new_account_1.address,
)
```

**Comment by faineance** [comment]
You can also use `sk.to_pem().decode()` and `SigningKey.from_pem` to serialise the private keys as strings. ( `SigningKey` can be imported from `ecdsa` )

**Comment by digitalronin** [comment]
I thought it would be me misunderstanding something simple! Many thanks for your help.
